@baseUrl = https://localhost:5207

### Создать проект
POST {{baseUrl}}/api/projects
Content-Type: application/json

{ "name": "Веб-сайт", "description": "Корпоративный портал" }

### Получить все
GET {{baseUrl}}/api/projects

### Получить по ID
GET {{baseUrl}}/api/projects/1

### Обновить
PUT {{baseUrl}}/api/projects/1
Content-Type: application/json

{ "name": "Веб-сайт v2", "description": "Обновлённый портал" }

### Удалить
DELETE {{baseUrl}}/api/projects/1

### Создать задачу
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{ "title": "Сверстать главную", "status": "ToDo", "projectId": 1 }

### Получить задачу
GET {{baseUrl}}/api/tasks/1