@baseUrl = https://localhost:5207

### Создать проект
POST {{baseUrl}}/api/projects
Content-Type: application/json

{ "name": "Веб-сайт", "description": "Корпоративный портал" }

### Получить все
GET {{baseUrl}}/api/projects

### Получить по ID
GET {{baseUrl}}/api/projects/1

### Обновить
PUT {{baseUrl}}/api/projects/1
Content-Type: application/json

{ "name": "Веб-сайт v2", "description": "Обновлённый портал" }

### Удалить
DELETE {{baseUrl}}/api/projects/1

### Создать задачу
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{ "title": "Сверстать главную", "status": "ToDo", "projectId": 1 }

### Получить задачу
GET {{baseUrl}}/api/tasks/1

### Пустое имя → 400
POST {{baseUrl}}/api/projects
Content-Type: application/json

{ "name": "", "description": "test" }

### Короткое имя → 400
POST {{baseUrl}}/api/projects
Content-Type: application/json

{ "name": "ab", "description": "test" }

### Задача: DueDate в прошлом → 400
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{ "title": "Новая задача", "projectId": 1, "dueDate": "2020-01-01T00:00:00Z" }

### Задача: короткий Title → 400
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{ "title": "abc", "projectId": 1 }